# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Nick Pachulski
paginate:       100
baseurl:        ""
url:            "pachulski.me"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Nick Pachulski
  url:          http://pachulski.me
  email:        nick@pachulski.me

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/pachun/pachun.github.io

# Gems
plugins:
  - jekyll-paginate
